null start teste null null null 
null read a null null null 
null read b null null null 
null read c null null null 
null macro null null null null 
null multsc a b c null 
null load a null null null 
null mult b null null null 
null shiftr 3 null null null 
null store c null null null 
null mend null null null null 
null macro null null null null 
null divsc a b c null 
null load a null null null 
null div b null null null 
null shiftl 3 null null null 
null store c null null null 
null mend null null null null 
lab multsc x z temp1 null 
null multsc temp1 @4 temp1 null 
null multsc x y temp2 null 
null sub temp1 null null null 
null store k null null null 
lab multsc x z temp1 null 
null multsc temp1 @4 temp1 null 
null multsc x y temp2 null 
null sub temp1 null null null 
null store k null null null 
null write d null null null 
null stop null null null null 
null a space null null null 
null b space null null null 
null c space null null null 
null d space null null null 
null temp1 space null null null 
null temp2 space null null null 
null end null null null null 
