null start teste null null null 
null read a null null null 
null read b null null null 
null read c null null null 
null scale 3 null null null 
null discr a b c d 
null discr x y z k 
null write d null null null 
null stop null null null null 
null a space null null null 
null b space null null null 
null c space null null null 
null d space null null null 
null temp1 space null null null 
null temp2 space null null null 
null end null null null null 
