null start teste null null null 
null read a null null null 
null read b null null null 
null read c null null null 
null load a null null null 
null mult c null null null 
null shiftr 3 null null null 
null store temp1 null null null 
null load temp1 null null null 
null mult @4 null null null 
null shiftr 3 null null null 
null store tempZ null null null 
null load a null null null 
null mult b null null null 
null shiftr 3 null null null 
null store temp2 null null null 
null sub temp1 null null null 
null store x null null null 
null write d null null null 
null stop null null null null 
null a space null null null 
null b space null null null 
null c space null null null 
null d space null null null 
null temp1 space null null null 
null temp2 space null null null 
null end null null null null 
