null start teste null 
null read a null 
null read b null 
null read c null 
null load a null 
null mult c null 
null store temp1 null 
null load temp1 null 
null mult @4 null 
null store temp2 null 
null load a null 
null mult b null 
null store temp2 null 
null sub temp1 null 
null store d null 
null write d null 
null stop null null 
a space null null 
b space null null 
c space null null 
d space null null 
temp1 space null null 
temp2 space null null 
null end null null 
