null start ex2 null 
null read a null 
null load a null 
null mult a null 
null store b null 
null write a null 
null write b null 
null stop null null 
a space null null 
b space null null 
null end null null 
