null start teste null 
null read a null 
null load a null 
null mult @a null 
null mult a null 
null mult a null 
null store b null 
null write a null 
null stop null null 
a space null null 
b space null null 
null end null null 
